sonar.projectKey=pe.victoryordi:kunturpay-event-platform
sonar.projectName=KunturPay Event Platform
sonar.sources=src/main
sonar.tests=src/test
sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.exclusions=**/config/**,**/*Application.java,**/entity/**
sonar.sourceEncoding=UTF-8
