apiVersion: v1
kind: ConfigMap
metadata:
  name: paycore-config
  namespace: paycore
data:
  DB_URL: jdbc:postgresql://postgres.example.internal:5432/paycore
  DB_USER: paycore
  REDIS_HOST: redis.example.internal
  REDIS_PORT: "6379"
  KAFKA_BOOTSTRAP_SERVERS: kafka.example.internal:9092
  PAYMENT_EVENTS_TOPIC: kunturpay.payments.v1
  SERVER_PORT: "8080"
  DB_POOL_MAX_SIZE: "20"
  DB_POOL_MIN_IDLE: "4"
