apiVersion: v1
kind: Service
metadata:
  name: paycore-api
  namespace: paycore
  labels:
    app.kubernetes.io/name: paycore-api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: paycore-api
  ports:
    - name: http
      port: 80
      targetPort: http
